---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main

inputs:
  - name: deployments-src
  - name: bosh-cpi-release
  - name: bosh-cli
  - name: concourse
  - name: garden-runc-release
  - name: worker-state
  - name: stemcell

outputs:
  - name: updated-worker-state

params:
  IAAS_CREDENTIALS:  ""
  OPTIONAL_FLAGS:    ""

run:
  path: deployments-src/ci/tasks/delete-worker
