---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/bosh-concourse-deployments

inputs:
  - name: input-src
  - name: deployments-src

outputs:
  - name: output-src

params:
  GIT_ADD_ARGS: ""
  GIT_COMMIT_MSG: ""
  GIT_COMMIT_USERNAME: ""
  GIT_COMMIT_EMAIL: ""
  GIT_SUCCEED_ON_NO_CHANGES: false

run:
  path: deployments-src/ci/tasks/git-commit
